services:
  - type: web
    name: top30-moud-analysis
    runtime: python
    rootDir: top30_comments_app
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
